###
GET http://localhost:8080/weather-info?pincode=629151&for_date=17/10/2024
Accept: application/json


### open weather api
GET https://api.openweathermap.org/data/2.5/weather?q=629151&appid=bef1e54f79aaad3124c47495202adc2c
