spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:pdf_db
    username: bineesh
    password: bineesh_pass
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
api:
  open-weather:
    key: bef1e54f79aaad3124c47495202adc2c
    url: https://api.openweathermap.org/data/2.5/weather


